#!/usr/bin/env python3
"""Generate genuine DA-style catalogue copy for every clean resource in the KB.

Uses the WORKING query-time structured-JSON mechanism (POST /ask with
answer_json_schema, scoped to a single resource via resource_filters) - NOT the
confirmed-broken ingest-time DA Generator task path. This is a real ARAG
extraction over the resource's own unstructured text, satisfying B10 (rich
listing copy generated by ARAG, not hardcoded) and B28 (the extraction must be
a genuine ARAG call, tested live) honestly - the solution-architecture reveal
names this as its mechanism.

Writes data/catalog_copy.json: {resource_id: {hook, highlights[], category, chips[]}}

Run: .venv/bin/python scripts/generate_catalog_copy.py [--limit N] [--resume]
"""
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent

CATEGORIES = [
    "Beach & Water", "Wildlife & Nature", "Culture & History",
    "Cycling & Walking Trails", "Accommodation", "Getting Here & Around",
    "Seasonal Guide & Itinerary", "Practical Info",
]

SCHEMA = {
    "name": "catalogue_copy",
    "description": "Punchy, honest catalogue listing copy generated from this page's own real content.",
    "parameters": {
        "type": "object",
        "properties": {
            "hook": {
                "type": "string",
                "description": "One punchy sentence (under 18 words) that would make a visitor want to click this card. Written from the page's real content only.",
            },
            "highlights": {
                "type": "array",
                "items": {"type": "string"},
                "minItems": 2,
                "maxItems": 3,
                "description": "2-3 short, concrete highlights (under 8 words each) drawn only from this page's own content.",
            },
            "category": {
                "type": "string",
                "enum": CATEGORIES,
                "description": "The single best-fit category for this page.",
            },
            "chips": {
                "type": "array",
                "items": {"type": "string"},
                "minItems": 1,
                "maxItems": 4,
                "description": "1-4 short scannable tags (2-3 words max each) - e.g. family-friendly, easy walk, snorkelling, free entry, bookings required - drawn only from what the page actually says.",
            },
        },
        "required": ["hook", "highlights", "category", "chips"],
    },
}


def load_env():
    env = {}
    for line in (APP_DIR / ".env").read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip()
    return env


def ask_structured(kb_url, token, resource_id, title):
    payload = json.dumps({
        "query": f"Generate catalogue listing copy for the page titled '{title}'.",
        "answer_json_schema": SCHEMA,
        "citations": False,
        "show": ["basic"],
        "resource_filters": [resource_id],
        "search_configuration": "rottnest-concierge",
    }).encode()
    req = urllib.request.Request(
        f"{kb_url}/ask", data=payload,
        headers={"X-NUCLIA-SERVICEACCOUNT": f"Bearer {token}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        body = r.read().decode()
    for line in body.splitlines():
        if not line.strip():
            continue
        d = json.loads(line)
        item = d.get("item", {})
        if item.get("type") == "answer_json":
            return item.get("object")
        if item.get("type") == "error":
            raise RuntimeError(str(item))
    raise RuntimeError("no answer_json in response")


def main():
    env = load_env()
    kb_url = env["KB_URL"]
    token = env["KB_TOKEN"]

    cache = json.loads((APP_DIR / "data" / "resource_cache.json").read_text())
    out_path = APP_DIR / "data" / "catalog_copy.json"
    results = {}
    if "--resume" in sys.argv and out_path.exists():
        results = json.loads(out_path.read_text())

    limit = None
    if "--limit" in sys.argv:
        limit = int(sys.argv[sys.argv.index("--limit") + 1])

    items = [(rid, r["title"]) for rid, r in cache.items() if rid not in results]
    if limit:
        items = items[:limit]

    print(f"Generating copy for {len(items)} resources (already have {len(results)})...", file=sys.stderr)
    errors = []
    for i, (rid, title) in enumerate(items):
        try:
            obj = ask_structured(kb_url, token, rid, title)
            results[rid] = obj
        except Exception as e:  # noqa: BLE001
            errors.append((rid, title, str(e)))
        if (i + 1) % 10 == 0:
            out_path.write_text(json.dumps(results, indent=2))
            print(f"  ...{i + 1}/{len(items)} (saved checkpoint)", file=sys.stderr)
        time.sleep(0.1)

    out_path.write_text(json.dumps(results, indent=2))
    print(f"Wrote {len(results)} entries to {out_path}", file=sys.stderr)
    if errors:
        print(f"{len(errors)} errors:", file=sys.stderr)
        for rid, title, err in errors[:20]:
            print(f"  {rid} ({title}): {err}", file=sys.stderr)


if __name__ == "__main__":
    main()
